Description: 
   Services reuired for the Webapp to be hosted 

Parameters:


  WorkflowID:
      Description: An environment name that will be prefixed to resource names
      Type: String
      Default: "1"
  


Resources:

  LBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue: "VPC"
      GroupDescription: Allow HTTP from anywhere, and HTTP to the Web Servers
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
    

  TargetGroup:  #The Amazon Resource Names (ARN) of the Elastic *Load Balancing target groups* to associate with the Auto Scaling group.
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId:
        Fn::ImportValue:  "VPC"
      Port: 80
      Protocol: HTTP
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Tags: 
        - Key: Identifier
          Value: !Sub ${WorkflowID}
    

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name:  "LoadBalancer"
      Subnets:
        - Fn::ImportValue:  "Public-Subnet1"
        - Fn::ImportValue:  "Public-Subnet2"
      SecurityGroups:
        - !Ref LBSecurityGroup
      Tags: 
        - Key: Name
          Value: !Sub ${WorkflowID}
  

  LBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: path-pattern
          Values:
            - "/*"    # any pattern
      ListenerArn: !Ref LBListener
      Priority: 1
  

  JumpboxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue: "VPC"
      GroupDescription: Allow SSH from anywhere
      SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0  
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0    

  Jumpbox:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0574da719dca65348
      SecurityGroupIds: 
        - Ref: JumpboxSecurityGroup 
      KeyName: nada
      SubnetId:
        Fn::ImportValue:  "Public-Subnet1"

  # InstanceSecurityGroup:
  #     Type: AWS::EC2::SecurityGroup
  #     Properties:
  #       VpcId: !Ref "VPC"
          
  #       GroupDescription: Allow SSH from anywhere
  #       SecurityGroupIngress:
  #         - IpProtocol: tcp
  #           FromPort: 22
  #           ToPort: 22
  #           CidrIp: 0.0.0.0/0  
  #       SecurityGroupEgress:
  #         - IpProtocol: tcp
  #           FromPort: 0
  #           ToPort: 65535
  #           CidrIp: 0.0.0.0/0    

  #   Instance:
  #     Type: AWS::EC2::Instance
  #     Properties:
  #       InstanceType: t2.micro
  #       ImageId: ami-0574da719dca65348
  #       SecurityGroupIds: 
  #         - Ref: InstanceSecurityGroup 
  #       KeyName: nada
  #       SubnetId: !Ref PublicSubnet
      
     
Outputs:

  JumpboxPublicHostname:
    Description: The Public IP Address of Jumpbox 
    Value: !GetAtt Jumpbox.PublicIp


  LoadBalancerDNSName:
    Description: DNS Name of the web application
    Value: !Join
      - ""
      - - "http://"
        - !GetAtt LoadBalancer.DNSName
    Export:
      Name:  !Sub "${WorkflowID}-ELB-DNS-Name"

  # WorkflowID:
  #   Value: !Sub ${WorkflowID}
  #   Description: Work flow number of old stack 
  #   Export:
  #     Name: !Sub WorkflowID-${WorkflowID}

  TargetGroup:
    Description: LB Target group id 
    Value: !Ref  TargetGroup
    Export:
      Name: TargetGroup

